### ISSUE TITLE
Inconsistent behavior between process.extractOne and fuzz.ratio

### ISSUE THREAD

**Issue by TrigonaMinima** [rapidfuzz/RapidFuzz#29]
I am using rapidfuzz for similarity of [devanagari](https://en.wikipedia.org/wiki/Devanagari) words. Here's a reproducible example.

```python
from rapidfuzz import fuzz, process

word = 'मस्सा'
wordlist = {'शर्ट', 'वर्ट', 'वार्ट', 'वऑर्ट', 'वॉर्ट'}

process.extractOne(word, wordlist)
# gives: ('वार्ट', 100.0)

for i in wordlist: print(fuzz.ratio(i, word))
# gives
# 22.22222222222222
# 22.22222222222222
# 19.999999999999996
# 19.999999999999996
# 19.999999999999996
```
In the output of `process.extractOne` best score should be `22.22` instead of `100.0`.

## Environment
Python: 3.6.10
Rapidfuzz: 0.7.8

**Comment by maxbachmann** [comment]
I am not quite sure how to handle this properly. E.g. 'शर्ट' is representated as `0x936, 0x930, 0x94d, 0x91f` apparently these are detected as punctuation and therefore replaced by whitespaces by the default_processor. (internally RapidFuzz is using widestrings, which are used by python aswell)

I am open to ideas on how to handle this better, but for now the best approach is to pass `processor=None` to all functions that use a processor by default (all but fuzz.ratio and fuzz.partial_ratio` (when you have a python function that handles preprocessing better you can pass processor=<your_func> to all of them aswell). So e.g.
```python
from rapidfuzz import fuzz, process
word = 'मस्सा'
wordlist = {'शर्ट', 'वर्ट', 'वार्ट', 'वऑर्ट', 'वॉर्ट'}

process.extractOne(word, wordlist, processor=None)
# gives: ('शर्ट', 22.22222222222222)
```

**Comment by TrigonaMinima** [comment]
I didn't check the function help for `processor=None` option. Using it kind of make things less accurate if I haven't done any preprocessing myself. Providing a preprocessing func will likely increase the time a bit.

I don't have knowledge of widestrings, but may be we can consider punctuation to be only what `string.punctuation` contains.

```python
import string
print(string.punctuation)
# !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```

or maybe we can create a big regex of punctuation characters, but again if this is an implementation detail within widestrings then I guess it's out of scope here.

Also, have you thought of working on a documentation page or a function reference page for the module?

**Comment by maxbachmann** [comment]
Hm yes I suppose the list c++ uses for `ispunct` probably contains some unwanted characters. I will create a big list of all characters to replace from punctuation, whitespaces (e.g. tabs), special characters (e.g. embedded null characters) with whitespaces.

A more complete documentation for all the functions is on my ToDo list https://github.com/maxbachmann/rapidfuzz/issues/17

**Comment by maxbachmann** [comment]
This should be fixed in v0.7.9
And I am simply iterating over the string comparing the characters since it is a lot faster than using a regex for this ;)

**Comment by TrigonaMinima** [comment]
I think there's still an issue with punctuation. Here's another reproducible example:

```python
from rapidfuzz import fuzz, process

word = "zetta"
wordlist = {'aan-', 'a-', 'an-', 'ant-', 'am-'}

process.extractOne(word, wordlist)
# gives: ('a-', 90.0)

[(i, fuzz.ratio("zetta", i)) for i in {'aan-', 'a-', 'an-', 'ant-', 'am-'}]
# gives:
# aan- 22.22222222222222
# a- 28.57142857142857
# an- 25.0
# ant- 22.22222222222222
# am- 25.0
```

**Comment by TrigonaMinima** [comment]
And still erroneous for devanagari chars. Here's another case:

```python
word = "दीवार"
wordlist = {'वाल्ल', 'वा', 'वॉल', 'वाल्', 'वाल'}

process.extractOne(word, wordlist)
# ('वा', 90.0)

for i in wordlist: print(fuzz.ratio(i, word))
# 40.0
# 57.14285714285714
# 25.0
# 44.44444444444444
# 50.0
```

**Comment by maxbachmann** [comment]
```
from rapidfuzz import fuzz, process

word = "zetta"
wordlist = {'aan-', 'a-', 'an-', 'ant-', 'am-'}

process.extractOne(word, wordlist)
# gives: ('a-', 90.0)

[(i, fuzz.ratio("zetta", i)) for i in {'aan-', 'a-', 'an-', 'ant-', 'am-'}]
# gives:
# aan- 22.22222222222222
# a- 28.57142857142857
# an- 25.0
# ant- 22.22222222222222
# am- 25.0
```
what is your expected result here? from a first look I can not see what is unexpected here. `process.extractOne` uses `fuzz.WRatio` by default which is a combination of `fuzz.ratio`, `fuzz.token_sort_ratio` and `fuzz.token_set_ratio`. So when you want it to use `fuzz.ratio` you should call

```
process.extractOne(word, wordlist, scorer=fuzz.ratio)
```

I can not see what your expected result for the devanagari chars are either.

**Comment by TrigonaMinima** [comment]
Okay, so from the looks of it, the similarity between `zetta` and `a-` cannot be `90.0`, even if you sort or take a set of the word chars. If i check this by using the specific `fuzz.*ratio` functions, here's the result:

```python
from rapidfuzz import fuzz

word1 = "zetta"
word2 = "a-"

fuzz.ratio(word, "a-")
# 28.57142857142857

fuzz.token_sort_ratio(word, "a-")
# 33.333333333333336

fuzz.token_set_ratio(word, "a-")
# 33.333333333333336

fuzz.WRatio(word, "a-")
# 90.0
```

Expected result will not be `90%` similarity doesn't matter how you look at it.

PS: Wasn't aware of the `scorer=` argument. Thanks.

**Comment by maxbachmann** [comment]
This is simply how fuzzywuzzy works. In this case the following steps are performed:
"zetta" <-> "a-"
lowercase and replace punctuation with whitespace
"zetta" <-> "a "
trim whitespace
"zetta" <-> "a"
since the longer string is more than 1.5 times (but less than 8 times longer) than the shorter string use partial_ratio instead of the normal ratio for a many comparisions. Since "a" is a substring of "zetta" this is a 100% match. then afterwards this is multiplied with 0.9 (0.6 when it is more than 8 times longer) -> the result is 90%

in your case with a length difference between 1.5x and 8x it executes:
- fuzz.ratio("zetta", "a")
- fuzz.partial_ratio("zetta", "a") * 0.9
- fuzz.partial_token_sort_ratio("zetta", "a") * 0.9 * 0.95
- fuzz.partial_token_set_ratio("zetta", "a") * 0.9 * 0.95

for strings with a length difference greater 8x:
- fuzz.ratio("zetta", "a")
- fuzz.partial_ratio("zetta", "a") * 0.6
- fuzz.partial_token_sort_ratio("zetta", "a") * 0.6 * 0.95
- fuzz.partial_token_set_ratio("zetta", "a") * 0.6 * 0.95

and when the length difference is smaller than 1.5x:
- fuzz.ratio("zetta", "a")
- fuzz.token_sort_ratio("zetta", "a") * 0.95
- fuzz.token_set_ratio("zetta", "a") * 0.95


Apparently it would be good to have this documented in a better way ;)

**Comment by TrigonaMinima** [comment]
Oh. So this is the classic, "not a bug, but a feature" scenario :smile: 

Yeah documentation should help. Still this looks like counter-intuitive to have a `90%` match for this pair specifically. Is there any basis in the choices of length differences (1.5x and 8x) and the multipliers (0.9 or 0.95)?

**Comment by maxbachmann** [comment]
I agree with you that this behaviour is not always wanted. I suppose Seatgeek simply had good results with this weighting for the data they are working with and I simply copied it since I wanted to have the same behaviour as FuzzyWuzzy (the docs of fuzzywuzzy only mention the weightings but not the reason either https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/fuzz.py#L225) ;)

I guess thats a usual thing about working with this kind of data that there is no single matching algorithm that fits all needs and you have to choose the one that fits the data your working on the best

**Comment by TrigonaMinima** [comment]
Yeah fair. Gotta put these things in the documentation though.
